language: emacs-lisp
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask
env:
  - EVM_EMACS=emacs-26.1-bin
  - EVM_EMACS=emacs-25.3-bin
script:
  - emacs --version
  - make test
