language: emacs-lisp
before_install:
  - curl -fsSkL https://raw.github.com/rejeep/evm/master/go | bash
  - export PATH="$HOME/.evm/bin:$PATH"
  - evm config path /tmp
  - evm install $EVM_EMACS --use
  - curl -fsSkL https://raw.github.com/cask/cask/master/go | python
  - export PATH="$HOME/.cask/bin:$PATH"
  - cask
  # - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  # - evm install $EVM_EMACS --use --skip
  # - cask
env:
  - EVM_EMACS=emacs-26.1-travis
  - EVM_EMACS=emacs-25.3-travis
  - EVM_EMACS=emacs-24.5-travis
script:
  - emacs --version
  - make test
